### ISSUE TITLE
[Bug Report]: Some (Two handed?) MCD Weapons delete anything in the off hand

### ISSUE THREAD

**Issue by finnglink** [chronosacaria/MCDungeonsWeapons#241] opened 2023-08-24 10:49 UTC
### Describe the bug; What happened?

Tested with Torches, Bread and a Shield, and the Vicious Hawkbrand and the Anchor. As soon as I select the hotbar slot the weapon is in, the off hand is cleared and its contents deleted. 

### Expected Behavior

Don't :D

### Mod Version

8.0.3

### Minecraft Launcher

Other

### Operating System

MacOS

### Modpack

Custom Fabric Modpack

**Comment by finnglink** [comment] 2023-08-24 10:51
Other Combat/Player related mods I have installed:

- Better Combat
- Axes Are Weapons
- Combat Roll
- YDM's Weapon Master
- NotEnoughAnimations

**Comment by chronosacaria** [comment] 2023-08-24 16:14
@finnglink Just making sure: is it deleted or you can't see it? Better Combat makes the Hawkbrand a two handed sword, which hides the item in your offhand whilst it is equipped. Upon unequipping the Hawkbrand, those items should return

**Comment by finnglink** [comment] 2023-08-24 16:17
@chronosacaria that's what I thought, but they're gone completely. The don't jump to another slot / stack, and once I go back to a different hotbar slot, it's just empty.

**Comment by chronosacaria** [comment] 2023-08-24 16:20
Okay. This sounds like it might be an issue with Better Combat and another mod because it doesn't happen with just MCDW. I'd encourage you to open an issue on the Better Combat GitHub, as well. I'll leave this open until I can touch base with Daedelus

**Comment by chronosacaria** [comment] 2023-08-24 16:21
Thanks for responding so quickly, btw

**Comment by finnglink** [comment] 2023-08-24 16:42
Thanks! It has only occurred to me so far with MCDW, but I'll check with simply swords, some of those should be two handed as well. And I'll open an issue over at Better Combat.

**Comment by chronosacaria** [comment] 2023-08-25 20:36
@finnglink So it turns out that this is caused by a conflict between Origins and Better Combat. From what I understand, there is a fix in the works. Since this isn't related to MCDW, I'm gonna close this issue. Thanks for mentioning it, though!

**Closed as not planned** 2023-08-25 20:37 UTC
Labels: invalid
