### ISSUE TITLE
Certain crossbows dont work

### ISSUE THREAD

**Issue by SopsyHallow** [chronosacaria/MCDungeonsWeapons#60] opened 2021-09-22 01:13 UTC
Certain crossbows dont seem to work, they draw back but they never load the arrow and cant be fired. 

The Crossbows in question are;
      "Pride of the Piglins"
      "Nautical Crossbow"
      "Corrupted Crossbow"
      "baby Crossbow"
      "Dual Crossbow"
      "Veiled Crossbow"
      "Rapid Crossbow"

![2021-09-22_03 02 51](https://user-images.githubusercontent.com/91166883/134267883-fc44c7ac-f9c3-4a42-a751-2e416fa95018.png)

Might be a compatiability issue with a different mod, but it only affects a few crossbows so why it would only affect 7 of them if its compat issue. If it is a compatibility issue i have no idea which mod could cause it since i encountered this bug on a premade 1.17.1 modpack. [Modpack is named "Another Quality Modpack 2"]

**Comment by chronosacaria** [comment] 2021-09-22 01:25
Thank you for narrowing down the crossbows. I can, indeed, confirm that the issue is in this modpack as you are not the first person to mention it. However, I was not able to figure out what was causing the issue last time either. 

I will do some more testing this time around and see if I can't isolate the mod that is causing the conflict with MCDW and get this squared away. 

Thanks again!

**Comment by SopsyHallow** [comment] 2021-09-22 01:49
Thank you for looking into it and respond quickly.

Do you know if those bows by any chance have modified charge rates?
It's just an idea but the way they seem to not load looks like how vanilla crossbows with a broken quick charge enchant try to load but never finish.
Maybe the compatinility issue could be related to a mod that modifies enchants and thus breaks the bows? Idk, it's just an idea.

Either thank you!!

**Comment by chronosacaria** [comment] 2021-09-25 12:30
Okay, I finally found the problem. It took a bit, but it is related to Deep Mob Learning: Refabricated. I'll see what I can do to get this resolved. Thank you, again, for all of the help that you provided with identifying the particular crossbows that were affected

**Comment by Kluzzio** [comment] 2022-04-08 19:28
Addressed and Potentially fixed in: https://github.com/CafeteriaGuild/DeepMobLearning-Refabricated/pull/98

**Comment by Kluzzio** [comment] 2022-04-08 19:28
Prayge for merge

**Comment by chronosacaria** [comment] 2022-04-09 16:16
Kluzzio's commit was merged into DML and NathanPB has mentioned putting out a hotfix soon. Once that is out, this issue will be closed :)

**Comment by chronosacaria** [comment] 2022-04-09 16:20
Hotfix was apparently released yesterday! Woohoo! 
https://github.com/CafeteriaGuild/DeepMobLearning-Refabricated/releases/tag/1.18.2%2B0.5.5-beta

**Closed as completed by chronosacaria** 2022-04-09 16:20 UTC
