### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Developer2704** [chronosacaria/MCDungeonsWeapons#156] opened 2022-09-02 23:35 UTC
Animate the flail so it drags around and the chain moves just like in mc dungeons

**Comment by chronosacaria** [comment] 2022-09-02 23:35
This is something that we'd love to do, but we would need some help in doing it. Do you have any ideas?

**Comment by Developer2704** [comment] 2022-09-03 03:03
There are some open source rendering and animation apis on curseforge and GitHub that you could use to animate the flail and whip

**Comment by chronosacaria** [comment] 2022-09-05 16:31
@Developer2704 Oh? That's awesome. Do you happen to know the names of any of them?

**Comment by Developer2704** [comment] 2022-09-13 11:12
No, I don't.

**Comment by Developer2704** [comment] 2022-09-17 23:24
Maybe you could try geckolib

**Comment by Developer2704** [comment] 2022-09-26 17:40
Geckolib can animated items so it could work.

**Comment by chronosacaria** [comment] 2023-05-08 15:04
Duplicate of #134

**Closed as completed by chronosacaria** 2023-05-08 15:04 UTC
Labels: duplicate
