### ISSUE TITLE
Huge weapons with Backslot

### ISSUE THREAD

**Issue by Sikelone** [chronosacaria/MCDungeonsWeapons#129] opened 2022-07-24 18:58 UTC
When using the Backslot mod and putting weapons in one of your extra slots, it just grows to huge sizes as shown underneath
![2022-07-24_20 58 23](https://user-images.githubusercontent.com/76126309/180661912-38ed447b-bb4a-4525-b866-54c85fb51964.png)
![2022-07-24_20 58 25](https://user-images.githubusercontent.com/76126309/180661914-ed564bae-1ba7-41ed-806f-51f49e362faf.png)

**Comment by Kluzzio** [comment] 2022-07-25 13:38
Because this is a known issue that is a duplicate of an open issue, this will be closed. But thank you for reporting it.

**Closed as completed by Kluzzio** 2022-07-25 13:38 UTC
Labels: duplicate, Maybe a bug? Maybe not?
