### ISSUE TITLE
[Bug Report]: MCDW doesn't work properly with MCDE

### ISSUE THREAD

**Issue by misterSalad** [chronosacaria/MCDungeonsWeapons#244] opened 2023-09-06 17:22 UTC
### Describe the bug; What happened?

If you enchant weapon from MCDW using Runic Table (on screenshot i added fire aspect to swift striker) and it doesnt work (i also checked poisoning and some other enchants), on second and third screen i did the same but with vanilla weapon and weapon from simple swords. all mods I used are in last screen 

![1](https://github.com/chronosacaria/MCDungeonsWeapons/assets/49678575/0fba31d2-0541-4cbe-af08-59ad43681301)
![1-1](https://github.com/chronosacaria/MCDungeonsWeapons/assets/49678575/1c997086-ec77-4d79-bc28-a082ec2ef792)
![2](https://github.com/chronosacaria/MCDungeonsWeapons/assets/49678575/4179d20b-5111-4161-9c95-563c6db1e8d2)
![2-2](https://github.com/chronosacaria/MCDungeonsWeapons/assets/49678575/43587c4d-421b-4da1-993b-5fd5f1b11208)
![3](https://github.com/chronosacaria/MCDungeonsWeapons/assets/49678575/9911fd75-525a-4aac-902e-c70576948ea1)
![3-3](https://github.com/chronosacaria/MCDungeonsWeapons/assets/49678575/516bde44-7b9b-4f4f-9e10-2708e796afb4)
![7](https://github.com/chronosacaria/MCDungeonsWeapons/assets/49678575/07016e1b-210f-427b-b1f0-5f5a7571894e)

### Expected Behavior

the enchant applied to the sword should work properly

### Mod Version

5.0.13

### Minecraft Launcher

Vanilla

### Operating System

Windows

**Comment by chronosacaria** [comment] 2023-09-06 18:56
To follow up on this, I shall post what was posted in Discord:

We're still waiting for Iamnotagenius' investigation, but it appears that the issue is, indeed, most likely to be on MCDW. As this issue is present in a version of Minecraft that is no longer supported with MCDW, unless a pull request is made by someone to resolve the issue, a backport will not happen as the differences between 1.19.2 and 1.20.x are quite extensive (it is worth noting that MCDE is an exception to this as both Iamnotagenius and BackupCup have expressed a desire to support 1.19.x). However, these kinds of code changes are the reason why Timefall Development, in almost all cases, only supports the latest version of Minecraft. I would advise you to update to 1.20.x as the issue does not appear to be present from what testing I have done.

I shall wait for Iamnotagenius' investigation to conclude before marking this as resolved and closing the issue on GitHub

**Comment by chronosacaria** [comment] 2023-11-30 02:50
It appears that this was an issue on MCDE's end and it has been resolved. As such, this issue shall be closed.

**Closed as completed by chronosacaria** 2023-11-30 02:50 UTC
Labels: Maybe a bug? Maybe not?, Awaiting Response
