### ISSUE TITLE
Registry Remapping Failed: Received ID Map for minecraft:sound_event cotains IDs unknown to the receiver! mcdw:echo_sound

### ISSUE THREAD

**Issue by teefssi** [chronosacaria/MCDungeonsWeapons#42] opened 2021-04-24 10:32 UTC
I added a few mods to this server including this one, and recently encountered a problem (which is the title)
how do i fix this? Do I need to install another version? Both the server and our clients have 3.1.1.

**Comment by teefssi** [comment] 2021-04-24 10:33
![q0Qmj2b0SDiQc0bVAI2hqA](https://user-images.githubusercontent.com/83118356/115955811-847ea080-a52b-11eb-824b-ca37b1e8be30.png)

**Comment by chronosacaria** [comment] 2021-04-24 12:26
That's weird. I've not changed anything with the registry. You're sure that both versions are the same? That kind of error usually means that there is a version mismatch.

**Comment by chronosacaria** [comment] 2021-04-24 12:47
Yeah, I just tested using a local server and I was able to connect to it with both versions being 3.1.1. It is possible that there might be an out of date version on the client side. If that isn't the case, though, if you could send me the log file, that would be awesome since that might help diagnose the issue. :)

**Comment by chronosacaria** [comment] 2021-05-22 14:05
Due to the lack of a response and my inability to reproduce the error, I am going to close this issue. If you are still having issues, please feel free to reopen the issue.

**Closed by chronosacaria** 2021-05-22 14:05 UTC
