### ISSUE TITLE
enigma shot enchantment causes crash

### ISSUE THREAD

**Issue by TheRanker** [chronosacaria/MCDungeonsWeapons#114] opened 2022-04-21 15:01 UTC
**Describe the bug**
seems mcdw has a bad enchantment .  enigma shot damage.  a raider has one and fired an arrow.

**To Reproduce**
get shot by a mob holding bow and arrow with the enigma shot enchantment

**Expected behavior**
not crash

**Screenshots**
NA

**Please complete the following information:**
 - OS:Windows
 - Launcher CF
 - Mod Version4.2.5
 - Are you using a Modpack? [e.g. Yes, No; if Yes, which one]
https://www.curseforge.com/minecraft/modpacks/deathdusk

**Additional context**
[crash-2022-04-21_16.42.45-client.txt](https://github.com/chronosacaria/MCDungeonsWeapons/files/8532146/crash-2022-04-21_16.42.45-client.txt)

**Comment by chronosacaria** [comment] 2022-04-21 15:02
I can take a look at this right now. Thanks for the report!

**Comment by chronosacaria** [comment] 2022-04-21 15:35
@TheRanker, I cannot reproduce this issue in the latest version, 4.3.0. Please be advised that we have changed the way that enchantments are applied and updating will likely delete any weapons you have. If you find that you are able to reproduce this issue in the latest version, we'll take another look at it, but if not, this issue will be closed in 48 hours

**Comment by TheRanker** [comment] 2022-04-21 15:37
ty. will keep it in mind and let the dev know and test once updated.

**Comment by chronosacaria** [comment] 2022-04-21 15:49
Sounds like a plan! :D

**Comment by Kluzzio** [comment] 2022-04-26 14:10
I checked our code and this issue was fixed between 4.2.5 and 4.3.0. There was initially just a cast whereas now there is a check to ensure there is a PlayerEntity doing the damage before accessing the experience.

**Closed as completed by Kluzzio** 2022-04-26 14:10 UTC
Labels: Awaiting Response
