### ISSUE TITLE
echo and shockwave

### ISSUE THREAD

**Issue by gravitysurfer05** [chronosacaria/MCDungeonsWeapons#31] opened 2021-02-21 20:05 UTC
both of the enchantments in the title if procced on a player by attacking a mob beside a player will instantly kill them and wipe their inventory

**Comment by chronosacaria** [comment] 2021-02-22 14:13
I need more information that this. This is the first time that I am hearing about an issue like this from anyone. For example: do you have any other mods installed? Are you on a server or on the client? How did it happen and can it be reproduced? I need more to go on before I can consider this a bug on my end.

**Comment by gravitysurfer05** [comment] 2021-02-22 19:38
i have quite a few other mods installed, we are on a server, it can be reproduced it happened when someone killed a skeleton from a spawner while another player was in range of the shockwave effect, though we were able to recreate it with naturally spawning mobs

**Comment by chronosacaria** [comment] 2021-02-23 17:17
Can you reproduce it with just my mod? I've not been able to reproduce this issue

**Comment by chronosacaria** [comment] 2021-03-09 16:18
I've been unable to reproduce this issue nor has more information been provided. This issue will be closed for now.

**Comment by JustXoi** [comment] 2021-04-17 02:05
I've just had this issue. I killed a zombie next to my friend and it killed him and wiped his inventory. 
I was using Whispering Spear. 
He died to the aoe effect that killed the zombie.
There was also no death message saying I killed him.

Me: JustXoi
Friend: DreadGnomes
[Twitch VOD for recreation (Timestamp: 00:45:35)](https://www.twitch.tv/videos/990278729?t=00h45m35s)
We are running a fabric server and the other major mods we are playing with are [Origins](https://www.curseforge.com/minecraft/mc-mods/origins), [BetterNether](https://www.curseforge.com/minecraft/mc-mods/betternether), and [BetterEnd](https://www.curseforge.com/minecraft/mc-mods/betterend).

**Comment by chronosacaria** [comment] 2021-04-17 09:11
Which version are you guys using? This issue should be fixed as of version 3.0.8, though I would suggest grabbing the latest version

**Comment by JustXoi** [comment] 2021-04-17 20:27
We're using 3.0.5. We didn't realize there was a patch. Sorry for any confusion.

**Comment by chronosacaria** [comment] 2021-04-17 20:34
No worries! I'm gonna close the issue since it is technically a resolved problem. :)
If you want, I suggest joining my Discord so you can get updates on my mods and when I release updates. Here is a link if you want to join: [https://discord.gg/WmpNkeV7](https://discord.gg/WmpNkeV7)

**Closed** 2021-04-17 20:34 UTC
