### ISSUE TITLE
[Bug Report]: 1.19.2 game crash on startup 

### ISSUE THREAD

**Issue by Cyberdragon577** [chronosacaria/MCDungeonsWeapons#231] opened 2023-07-06 09:11 UTC
### Describe the bug; What happened?

When i boot up minecraft it carshes and gives me exit code -1

[crash-2023-07-06_04.04.48-client.txt](https://github.com/chronosacaria/MCDungeonsWeapons/files/11966533/crash-2023-07-06_04.04.48-client.txt)

### Expected Behavior

minecraft to load without any problems

### Mod Version

5.0.13

### Minecraft Launcher

Vanilla

### Operating System

Windows

**Comment by chronosacaria** [comment] 2023-07-06 13:16
@Cyberdragon577 I could not find a way to reproduce this. Remove Optifine and OptiFabric and use Sodium and Iris instead. This is most likely what is causing your problem

**Comment by Cyberdragon577** [comment] 2023-07-07 09:46
That worked, but did it not crash for you when using Optifine?

**Comment by chronosacaria** [comment] 2023-07-07 19:17
@Cyberdragon577 I don't use Optifine because it won't launch properly in my dev environment. When I couldn't reproduce it without Optifine, I figured that was the issue. Glad that resolved it, though. I'm gonna close the issue :)

**Closed as completed by chronosacaria** 2023-07-07 19:17 UTC
Labels: Maybe a bug? Maybe not?, compatibility issue, Awaiting Response
