### ISSUE TITLE
Innate Enchantments ignore compatibility conflicts with other enchantments

### ISSUE THREAD

**Issue by Kluzzio** [chronosacaria/MCDungeonsWeapons#77] opened 2022-01-06 16:29 UTC
Innate enchantments are ignoring enchantment conflicts

"Moon dager can get enigma resoanator and void strike without activating the op mixture"
 - Xneverfound🎄

**Comment by chronosacaria** [comment] 2022-01-08 13:29
I cannot reproduce this on the latest version with the latest fixes outside of creative mode and without OP Mixing enabled. As such, I am going to close this issue.

**Closed as completed by chronosacaria** 2022-01-08 13:29 UTC
Labels: bug
