### ISSUE TITLE
[Bug Report]: Minecraft server doesnt start with this mod

### ISSUE THREAD

**Issue by Mihuto** [chronosacaria/MCDungeonsWeapons#247] opened 2023-10-05 16:26 UTC
### Describe the bug; What happened?

My game and server wont start after installing the mod. It only works when i remove this mod both from the server and the game itsself. Any solutions to make it work? When i start the game with this mod game error code 1 pops up. I added the server log in the context for more information

### Expected Behavior

It should work normally instead of crashing instantly

### Mod Version

7.0.0

### Minecraft Launcher

Vanilla

### Operating System

Windows

### Modpack

None

### Additional context

[18:16:47] [main/ERROR]: Minecraft has crashed!
119 | net.fabricmc.loader.impl.FormattedException: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1792 failed
120 | at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.22.jar:?]
121 | at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.22.jar:?]
122 | at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
123 | at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.22.jar:?]
124 | at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.22.jar:?]
125 | Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1792 failed
126 | at net.minecraft.class_7923.<clinit>(class_7923.java:123) ~[server-intermediary.jar:?]
127 | at net.minecraft.class_2966.method_12851(class_2966.java:42) ~[server-intermediary.jar:?]
128 | at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
129 | at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
130 | ... 3 more
131 | Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1792 failed
132 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.22.jar:?]
133 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.22.jar:?]
134 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
135 | at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
136 | at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
137 | at net.minecraft.class_7923.<clinit>(class_7923.java:123) ~[server-intermediary.jar:?]
138 | at net.minecraft.class_2966.method_12851(class_2966.java:42) ~[server-intermediary.jar:?]
139 | at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
140 | at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
141 | ... 3 more
142 | Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
143 | at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
144 | at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
145 | at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
146 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.22.jar:?]
147 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.22.jar:?]
148 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
149 | at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
150 | at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
151 | at net.minecraft.class_7923.<clinit>(class_7923.java:123) ~[server-intermediary.jar:?]
152 | at net.minecraft.class_2966.method_12851(class_2966.java:42) ~[server-intermediary.jar:?]
153 | at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
154 | at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
155 | ... 3 more
156 | Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method getActualReachDistance(DLnet/minecraft/class_1937;Lnet/minecraft/class_1657;)D in mixins.reach-entity-attributes.json:ItemMixin from mod reach-entity-attributes failed injection check, (0/4) succeeded. Scanned 1 target(s). Using refmap refmap.reach-entity-attributes.json
157 | at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
158 | at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
159 | at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
160 | at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
161 | at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
162 | at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
163 | at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
164 | at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
165 | at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
166 | at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
167 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.22.jar:?]
168 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.22.jar:?]
169 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
170 | at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
171 | at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
172 | at net.minecraft.class_7923.<clinit>(class_7923.java:123) ~[server-intermediary.jar:?]
173 | at net.minecraft.class_2966.method_12851(class_2966.java:42) ~[server-intermediary.jar:?]
174 | at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
175 | at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
176 | ... 3 more
177

<br class="Apple-interchange-newline">
</body>
</html>[18:16:47] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1792 failed
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.22.jar:?]
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1792 failed
	at net.minecraft.class_7923.<clinit>(class_7923.java:[123](https://aternos.org/log/#L123)) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_[128](https://aternos.org/log/#L128)51(class_2966.java:42) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	... 3 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1792 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.class_7923.<clinit>(class_7923.java:123) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:42) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	... 3 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.class_7923.<clinit>(class_7923.java:123) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:42) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	... 3 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method getActualReachDistance(DLnet/minecraft/class_1937;Lnet/minecraft/class_1657;)D in mixins.reach-entity-attributes.json:ItemMixin from mod reach-entity-attributes failed injection check, (0/4) succeeded. Scanned 1 target(s). Using refmap refmap.reach-entity-attributes.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:[138](https://aternos.org/log/#L138)4) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.class_7923.<clinit>(class_7923.java:123) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:42) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	... 3 more

**Comment by chronosacaria** [comment] 2023-10-05 16:35
@Mihuto So there are a few things happening here that make it harder to figure out what is going on:
1. You've not provided a list of mods you're using
2. The issue is happening with a library that is being used by MCDW, not MCDW itself
3. The mod works on its own, so there is a conflict happening or the mod may have been altered in some way from downloading it from a place other than CurseForge
4. Only the latest version of Minecraft is supported

Please provide a list of mods that are being used, in text form — not an image (as I won't be able to read it as well) in order to assist in diagnosing what is going on. It is also advised to update to the latest version on Minecraft and MCDW

**Comment by Mihuto** [comment] 2023-10-07 19:31
Here is a list of the mods i used

- cloth config
- collective
- CorgiLib
- cristellib
- Croptopia
- extraorigins
- fabric api
- fabric language kotlin
- Falling Tree
- geckolib
- guard villagers
- health levels
- libraryferret
- midnightlib
- Oh The Biomes You'll Go Refabricated
- Origins
- origins ++
- paladin furniture mod
- Pehkui
- phospor
- randomvillagenames
- RoughlyEnoughItems (REI)
- skin restorer
- SmartBrainLib
- Marium's Soulslike Weaponry
- TerraBlender
- Towns and Towers
- veinmining
- villagernames
- waystones
- Xaeros Minimap

These are all mods, which are all on Fabric and on the latest version. My Minecraft version is on 1.19.4. Fabric.I have already installed the latest version of MCDW and this version was installed on curseforge.

**Comment by chronosacaria** [comment] 2023-10-07 21:08
@Mihuto Ah, okay. I see what is going on. This conflict with Reach Entity Attributes was resolved in later versions. Please consider updating to 1.20 or 1.20.1. As is stated in the changelog for the 1.19.4 release:
> This will be the ONLY 1.19.4 release
As such, later bug fixes will not be backported. We thank you for your understanding

**Closed as completed by chronosacaria** 2023-10-07 21:08 UTC
Labels: Maybe a bug? Maybe not?, Awaiting Response
